import Brand from '../components/Brand';
import Icon from '../components/Icon';

export default function AuthLayout({ children, title, eyebrow, subtitle }) {
  return <div className="grid min-h-screen bg-slate-950 lg:grid-cols-[minmax(0,1.1fr)_minmax(420px,.9fr)]">
    <section className="relative hidden overflow-hidden px-10 py-10 text-white lg:flex lg:flex-col xl:px-20"><div className="absolute inset-0 dot-grid opacity-60" /><div className="absolute -left-20 top-16 h-80 w-80 rounded-full bg-cyan-500/15 blur-3xl" /><div className="absolute bottom-0 right-0 h-96 w-96 rounded-full bg-blue-600/20 blur-3xl" /><div className="relative z-10"><Brand light /><div className="mt-28 max-w-xl xl:mt-36"><div className="mb-6 flex items-center gap-2 text-sm font-semibold text-cyan-300"><span className="h-px w-8 bg-cyan-400" />INTELLIGENT DOCUMENT PROCESSING</div><h1 className="text-5xl font-bold leading-[1.08] tracking-[-0.04em] xl:text-6xl">Make every document <span className="text-cyan-300">work smarter.</span></h1><p className="mt-7 max-w-md text-base leading-7 text-slate-400">Turn invoices and bills into clean, actionable data with a workspace designed for speed and confidence.</p></div><div className="relative mt-16 max-w-lg rounded-2xl border border-slate-800 bg-slate-900/80 p-5 shadow-2xl shadow-cyan-950/20 backdrop-blur"><div className="mb-4 flex items-center justify-between"><div className="flex items-center gap-2 text-xs font-semibold text-slate-300"><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-cyan-400/10 text-cyan-300"><Icon name="sparkles" size={15} /></span>AI extraction preview</div><span className="rounded-full bg-emerald-400/10 px-2 py-1 text-[10px] font-bold text-emerald-300">READY</span></div><div className="grid grid-cols-3 gap-2 text-xs">{['Vendor', 'Invoice no.', 'Total'].map((label, index) => <div className="rounded-xl bg-slate-800/80 p-3" key={label}><p className="text-slate-500">{label}</p><div className={`mt-2 h-2 rounded-full bg-slate-700 ${index === 2 ? 'w-4/5' : 'w-3/5'}`} /></div>)}</div></div></div><div className="relative z-10 mt-auto text-xs text-slate-600">© 2026 DocuMind workspace</div></section>
    <section className="soft-glow flex min-h-screen items-center justify-center px-5 py-10 sm:px-10"><div className="w-full max-w-md"><div className="mb-10 lg:hidden"><Brand /></div><div className="mb-8"><p className="mb-2 text-xs font-bold uppercase tracking-[.18em] text-cyan-600">{eyebrow}</p><h2 className="text-3xl font-bold tracking-tight text-slate-950">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{subtitle}</p></div>{children}</div></section>
  </div>;
}
